In [1]:
import numpy as np

In [2]:
%run ../../functions.py

In [3]:
temp = generate_numbers(21, 8, 0)
temp

[3, 11, 10, 19, 17, 9, 8, 13]

In [4]:
temp2 = generate_numbers(21, 8, 0)

In [5]:
arr_a = np.array(temp)
arr_b = np.array(temp2)

#### all arithmethics

In [6]:
arr_a + arr_b 

array([13, 15, 17, 36, 22, 15, 17, 32])

In [7]:
arr_a - arr_b

array([-7,  7,  3,  2, 12,  3, -1, -6])

In [8]:
arr_a * arr_b 

array([ 30,  44,  70, 323,  85,  54,  72, 247])

In [9]:
arr_b / arr_a 

array([3.33333333, 0.36363636, 0.7       , 0.89473684, 0.29411765,
       0.66666667, 1.125     , 1.46153846])

In [10]:
arr_b**arr_a 

array([               1000,             4194304,           282475249,
       2632489875535903793,        762939453125,            10077696,
                  43046721,   42052983462257059])

In [11]:
arr = np.array(temp)

In [12]:
new = 2*arr
new

array([ 6, 22, 20, 38, 34, 18, 16, 26])