In [13]:
import numpy as np
from numpy import linalg

In [14]:
%run ../../functions.py

In [15]:
# A = np.array([[3, -2, 1], [1, 1, -2], [-3, -2, 1]])
# b = np.array([7, -4, 1])

In [16]:
A = np.array(make_shape(generate_numbers(21, 9, 0), (3, 3)))
A

array([[ 8, 14, 13],
       [ 0,  7,  5],
       [ 6, 10, 16]])

In [17]:
b = np.array(make_shape(generate_numbers(13, 3, 0), (3, )))
b

array([12,  2,  4])

In [18]:
linalg.solve(A, b) 

array([ 1.27567568,  0.81081081, -0.73513514])