In [1]:
import numpy as np

In [2]:
%run ../functions.py

In [3]:
temp = generate_numbers(21, 8, 0)
temp

[20, 15, 11, 7, 17, 10, 9, 1]

In [4]:
temp2 = generate_numbers(21, 8, 0)

In [5]:
arr_a = np.array(temp)
arr_b = np.array(temp2)

In [6]:
arr_a + arr_b 

array([23, 28, 20, 12, 17, 26, 29,  5])

In [7]:
arr_a - arr_b

array([ 17,   2,   2,   2,  17,  -6, -11,  -3])

In [8]:
arr_a * arr_b 

array([ 60, 195,  99,  35,   0, 160, 180,   4])

In [9]:
arr_b / arr_a 

array([0.15      , 0.86666667, 0.81818182, 0.71428571, 0.        ,
       1.6       , 2.22222222, 4.        ])

In [10]:
arr_b**arr_a 

array([-808182895, 1788720133, 1316288537,      78125,          0,
                0,  898891776,          4])

In [11]:
arr = np.array(temp)

In [12]:
new = 2*arr
new

array([40, 30, 22, 14, 34, 20, 18,  2])