In [1]:
import numpy as np

In [2]:
%run ../functions.py

In [3]:
temp = generate_numbers(21, 8, 0)
temp

[4, 11, 2, 5, 17, 1, 6, 16]

In [4]:
temp2 = generate_numbers(21, 8, 0)

In [5]:
arr_a = np.array(temp)
arr_b = np.array(temp2)

#### all arithmethics

In [6]:
arr_a + arr_b 

array([ 9, 28, 20, 20, 28,  4, 12, 28])

In [7]:
arr_a - arr_b

array([ -1,  -6, -16, -10,   6,  -2,   0,   4])

In [8]:
arr_a * arr_b 

array([ 20, 187,  36,  75, 187,   3,  36, 192])

In [9]:
arr_b / arr_a 

array([1.25      , 1.54545455, 9.        , 3.        , 0.64705882,
       3.        , 1.        , 0.75      ])

In [10]:
arr_b**arr_a 

array([        625, -1942714447,         324,      759375,   -92658101,
                 3,       46656,           0])

In [11]:
arr = np.array(temp)

In [12]:
new = 2*arr
new

array([ 8, 22,  4, 10, 34,  2, 12, 32])