In [24]:
import numpy as np

In [25]:
%run ../functions.py

In [26]:
temp = generate_numbers(21, 8, 0)

In [27]:
temp2 = generate_numbers(21, 8, 0)

In [28]:
arr_a = np.array(temp)
arr_b = np.array(temp2)

In [29]:
arr_a + arr_b 

array([24, 28, 10,  9,  4, 25, 19, 30])

In [30]:
arr_a - arr_b

array([ 12,   2, -10,  -1,  -2,   3,   1,   2])

In [31]:
arr_a * arr_b 

array([108, 195,   0,  20,   3, 154,  90, 224])

In [32]:
arr_b / arr_a 

/tmp/ipykernel_27774/3949139376.py:1: RuntimeWarning: divide by zero encountered in divide
  arr_b / arr_a


array([0.33333333, 0.86666667,        inf, 1.25      , 3.        ,
       0.78571429, 0.9       , 0.875     ])

In [33]:
arr_b**arr_a 

array([    101559956668416,   51185893014090757,                   1,
                       625,                   3,     379749833583241,
                3486784401, 2177953337809371136])

In [34]:
arr = np.array(temp)

In [35]:
new = 2*arr
new

array([36, 30,  0,  8,  2, 28, 20, 32])