In [5]:
import numpy as np

In [6]:
%run ../functions.py

In [7]:
temp = generate_numbers(21, 9, 0)
temp

[6, 15, 2, 11, 14, 18, 17, 3, 0]

In [8]:
sample = make_shape(temp)

In [9]:
A = np.array(sample)
A

array([[ 6, 15,  2],
       [11, 14, 18],
       [17,  3,  0]])

In [10]:
# linear algebra, Compute the eigenvalues and right eigenvectors of a square array
v, B = np.linalg.eig(A)
v, B

(array([29.94423931 +0.j        , -4.97211966+10.20052488j,
        -4.97211966-10.20052488j]),
 array([[-0.51521554+0.j        , -0.14072846+0.48133136j,
         -0.14072846-0.48133136j],
        [-0.7731025 +0.j        , -0.31378072-0.44778196j,
         -0.31378072+0.44778196j],
        [-0.36995335+0.j        ,  0.67048385+0.j        ,
          0.67048385-0.j        ]]))

In [11]:
# Extract a diagonal or construct a diagonal array.
D = np.diag(v)
D

array([[29.94423931 +0.j        ,  0.         +0.j        ,
         0.         +0.j        ],
       [ 0.         +0.j        , -4.97211966+10.20052488j,
         0.         +0.j        ],
       [ 0.         +0.j        ,  0.         +0.j        ,
        -4.97211966-10.20052488j]])

In [12]:
A_reconstructed = np.dot(B, np.dot(D, np.linalg.inv(B)))
A_reconstructed

array([[ 6.00000000e+00+7.26009931e-17j,  1.50000000e+01+3.18157861e-16j,
         2.00000000e+00-1.40721016e-15j],
       [ 1.10000000e+01+1.97021954e-16j,  1.40000000e+01+3.24072694e-16j,
         1.80000000e+01-3.18876843e-15j],
       [ 1.70000000e+01-9.82176963e-17j,  3.00000000e+00+1.16200329e-15j,
        -1.38107393e-15-2.84760052e-15j]])

In [13]:
# B[0]    # array([ 0.73271846, -0.65131465,  0.19726352])

In [14]:
D2 = np.diag(B[0])
D2

array([[-0.51521554+0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        , -0.14072846+0.48133136j,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -0.14072846-0.48133136j]])

In [15]:
i = 0  
lambda0 = v[i]
lambda0

(29.944239312981967+0j)

In [16]:
x0 = B[:, i]    # get the first column of B
x0

array([-0.51521554+0.j, -0.7731025 +0.j, -0.36995335+0.j])

In [17]:
np.linalg.norm(x0)

0.9999999999999999

In [18]:
B

array([[-0.51521554+0.j        , -0.14072846+0.48133136j,
        -0.14072846-0.48133136j],
       [-0.7731025 +0.j        , -0.31378072-0.44778196j,
        -0.31378072+0.44778196j],
       [-0.36995335+0.j        ,  0.67048385+0.j        ,
         0.67048385-0.j        ]])

In [19]:
x1 = B[:, 1]
x1

array([-0.14072846+0.48133136j, -0.31378072-0.44778196j,
        0.67048385+0.j        ])

In [20]:
np.linalg.norm(x1)

1.0000000000000002

In [21]:
x2 = B[:, 2]
x2

array([-0.14072846-0.48133136j, -0.31378072+0.44778196j,
        0.67048385-0.j        ])

In [22]:
np.linalg.norm(x2)

1.0000000000000002

In [23]:
A

array([[ 6, 15,  2],
       [11, 14, 18],
       [17,  3,  0]])

In [24]:
lhs = A @ x0
lhs

array([-15.42773736+0.j, -23.14996615+0.j, -11.07797163+0.j])

In [25]:
lambda0

(29.944239312981967+0j)

In [26]:
rhs = lambda0*x0
rhs

array([-15.42773736+0.j, -23.14996615+0.j, -11.07797163+0.j])

In [27]:
np.linalg.norm(lhs - rhs)

1.2560739669470201e-14