In [50]:
import numpy as np

In [51]:
%run ../functions.py

In [52]:
temp = generate_numbers(21, 9, 0)
temp

[11, 8, 9, 3, 20, 15, 12, 10, 13]

In [53]:
sample = make_shape(temp)

In [54]:
A = np.array(sample)
A

array([[11,  8,  9],
       [ 3, 20, 15],
       [12, 10, 13]])

In [55]:
# linear algebra, Compute the eigenvalues and right eigenvectors of a square array
v, B = np.linalg.eig(A)
v, B

(array([34.48957297,  7.85724873,  1.6531783 ]),
 array([[-0.45216717, -0.39904546, -0.23584566],
        [-0.68499402,  0.75007961, -0.59169883],
        [-0.57125129, -0.52739292,  0.77088866]]))

In [56]:
# Extract a diagonal or construct a diagonal array.
D = np.diag(v)
D

array([[34.48957297,  0.        ,  0.        ],
       [ 0.        ,  7.85724873,  0.        ],
       [ 0.        ,  0.        ,  1.6531783 ]])

In [57]:
A_reconstructed = np.dot(B, np.dot(D, np.linalg.inv(B)))
A_reconstructed

array([[11.,  8.,  9.],
       [ 3., 20., 15.],
       [12., 10., 13.]])

In [58]:
# B[0]    # array([ 0.73271846, -0.65131465,  0.19726352])

In [59]:
D2 = np.diag(B[0])
D2

array([[-0.45216717,  0.        ,  0.        ],
       [ 0.        , -0.39904546,  0.        ],
       [ 0.        ,  0.        , -0.23584566]])

In [60]:
i = 0  
lambda0 = v[i]
lambda0

34.489572974162755

In [61]:
B

array([[-0.45216717, -0.39904546, -0.23584566],
       [-0.68499402,  0.75007961, -0.59169883],
       [-0.57125129, -0.52739292,  0.77088866]])

In [62]:
x0 = B[:, i]    # get the first column of B
x0

array([-0.45216717, -0.68499402, -0.57125129])

In [63]:
np.linalg.norm(x0)

0.9999999999999999

In [64]:
x1 = B[:, 1]    # second column
x1

array([-0.39904546,  0.75007961, -0.52739292])

In [65]:
x2 = B[:, 2]   
x2

array([-0.23584566, -0.59169883,  0.77088866])

In [66]:
np.linalg.norm(x1)

0.9999999999999999

In [67]:
x2 = B[i, :]        # row 1st
# x2 = B[1, :]    # row 2nd
x2

array([-0.45216717, -0.39904546, -0.23584566])

In [68]:
np.linalg.norm(x2)

0.6475458325397574

In [69]:
A

array([[11,  8,  9],
       [ 3, 20, 15],
       [12, 10, 13]])

In [70]:
lhs = A @ x0    # matmul
lhs

array([-15.59505269, -23.62515133, -19.70221308])

In [71]:
lambda0

34.489572974162755

In [72]:
rhs = lambda0*x0
rhs

array([-15.59505269, -23.62515133, -19.70221308])

In [73]:
np.linalg.norm(lhs - rhs)

2.2539441496237913e-14