In [83]:
import numpy as np

In [84]:
A = np.array([[3, -1, 4], [-1, 0, -1], [4, -1, 2]])
A

array([[ 3, -1,  4],
       [-1,  0, -1],
       [ 4, -1,  2]])

In [85]:
# linear algebra, Compute the eigenvalues and right eigenvectors of a square array
v, B = np.linalg.eig(A)
v, B

(array([ 6.82315616, -1.53711415, -0.28604201]),
 array([[ 0.73271846, -0.65131465,  0.19726352],
        [-0.20260301,  0.06794858,  0.97690072],
        [ 0.64967352,  0.75575937,  0.08217113]]))

In [86]:
# Extract a diagonal or construct a diagonal array.
D = np.diag(v)
D

array([[ 6.82315616,  0.        ,  0.        ],
       [ 0.        , -1.53711415,  0.        ],
       [ 0.        ,  0.        , -0.28604201]])

In [87]:
A_reconstructed = np.dot(B, np.dot(D, np.linalg.inv(B)))
A_reconstructed

array([[ 3.00000000e+00, -1.00000000e+00,  4.00000000e+00],
       [-1.00000000e+00,  3.27065195e-16, -1.00000000e+00],
       [ 4.00000000e+00, -1.00000000e+00,  2.00000000e+00]])

In [88]:
# B[0]    # array([ 0.73271846, -0.65131465,  0.19726352])

In [89]:
D2 = np.diag(B[0])
D2

array([[ 0.73271846,  0.        ,  0.        ],
       [ 0.        , -0.65131465,  0.        ],
       [ 0.        ,  0.        ,  0.19726352]])

In [90]:
i = 0  
lambda0 = v[i]
lambda0

6.823156164525971

In [91]:
x0 = B[:, i]    # get the first column of B
x0

array([ 0.73271846, -0.20260301,  0.64967352])

In [92]:
np.linalg.norm(x0)

1.0

In [93]:
B

array([[ 0.73271846, -0.65131465,  0.19726352],
       [-0.20260301,  0.06794858,  0.97690072],
       [ 0.64967352,  0.75575937,  0.08217113]])

In [94]:
x1 = B[:, 1]
x1

array([-0.65131465,  0.06794858,  0.75575937])

In [95]:
np.linalg.norm(x1)

1.0

In [96]:
x2 = B[:, 2]
x2

array([0.19726352, 0.97690072, 0.08217113])

In [97]:
np.linalg.norm(x2)

0.9999999999999999

In [101]:
A

array([[ 3, -1,  4],
       [-1,  0, -1],
       [ 4, -1,  2]])

In [98]:
lhs = A @ x0
lhs

array([ 4.99945246, -1.38239198,  4.43282388])

In [102]:
lambda0

6.823156164525971

In [99]:
rhs = lambda0*x0
rhs

array([ 4.99945246, -1.38239198,  4.43282388])

In [100]:
np.linalg.norm(lhs - rhs)

2.8435583831733384e-15