In [50]:
import numpy as np

In [51]:
%run ../functions.py

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# mat = np.array([[1, 2], [3, 4]])
mat = np.array(make_shape(generate_numbers(13, 9, 0), (3, 3)))
mat

array([[ 2,  7, 12],
       [ 8,  9,  3],
       [ 1,  5,  4]])

In [54]:
mat.transpose()

array([[ 2,  8,  1],
       [ 7,  9,  5],
       [12,  3,  4]])

In [55]:
mat.T

array([[ 2,  8,  1],
       [ 7,  9,  5],
       [12,  3,  4]])

In [56]:
# A = np.array([[1, 2], [3, 4]])
A = np.array(make_shape(generate_numbers(21, 9, 0), (3, 3)))


In [57]:
A.trace()

19

In [58]:
# A = np.array([[1, 2], [3, 4]])
# B = np.array([[-1, 1], [0, 1]])
A = np.array(make_shape(generate_numbers(34, 9, 0), (3, 3)))
B = np.array(make_shape(generate_numbers(21, 9, 0), (3, 3)))
A @ B

array([[723, 658, 320],
       [619, 450, 326],
       [740, 502, 486]])

In [59]:
A * B

array([[224,  10,  27],
       [104,  85, 135],
       [  0, 608, 198]])

In [60]:
# A = np.array([[1, 2], [3, 4]])
A = np.array(make_shape(generate_numbers(34, 9, 0), (3, 3)))
I = np.eye(3)
A @ I

array([[29., 25., 10.],
       [11., 31.,  7.],
       [17., 32., 26.]])

In [61]:
from numpy import linalg
linalg.det(A)  

10953.000000000004

In [62]:
linalg.inv(A)

array([[ 0.05313613, -0.03012873, -0.01232539],
       [-0.01524696,  0.05331873, -0.00849082],
       [-0.01597736, -0.04592349,  0.05697069]])

In [63]:
Ainv = linalg.inv(A)
Ainv @ A

array([[ 1.00000000e+00,  1.11022302e-16,  1.04083409e-17],
       [ 1.56125113e-17,  1.00000000e+00, -3.81639165e-17],
       [ 8.32667268e-17,  0.00000000e+00,  1.00000000e+00]])

In [64]:
A @ Ainv

array([[ 1.00000000e+00,  4.16333634e-17, -5.55111512e-17],
       [ 1.56125113e-16,  1.00000000e+00, -2.77555756e-17],
       [ 2.15105711e-16, -6.93889390e-17,  1.00000000e+00]])