In [1]:
import numpy as np

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
mat = np.array([[1, 2], [3, 4]])
mat.transpose()

array([[1, 3],
       [2, 4]])

In [4]:
mat.T

array([[1, 3],
       [2, 4]])

In [5]:
A = np.array([[1, 2], [3, 4]])
A.trace()

5

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 1], [0, 1]])
A @ B

array([[-1,  3],
       [-3,  7]])

In [7]:
A * B

array([[-1,  2],
       [ 0,  4]])

In [8]:
A = np.array([[1, 2], [3, 4]])
I = np.eye(2)
A @ I

array([[1., 2.],
       [3., 4.]])

In [9]:
from numpy import linalg
linalg.det(A)  

-2.0000000000000004

In [10]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
Ainv = linalg.inv(A)
Ainv @ A

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [12]:
A @ Ainv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])