In [9]:
import numpy as np


In [10]:
ary = np.array([1, 2, 3, 4])  

In [11]:
ary[0] , ary[2], ary[::2]  

(1, 3, array([1, 3]))

In [12]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [13]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [14]:
arr.dtype = np.float32
arr

array([1.e-45, 0.e+00, 3.e-45, 0.e+00, 4.e-45, 0.e+00, 6.e-45, 0.e+00],
      dtype=float32)

In [15]:
arr2 = arr.astype(np.float32)
arr2

array([1.e-45, 0.e+00, 3.e-45, 0.e+00, 4.e-45, 0.e+00, 6.e-45, 0.e+00],
      dtype=float32)