In [30]:
import numpy as np


In [31]:
%run ../functions.py

In [32]:
# ary = np.array([1, 2, 3, 4])  
ary = np.array(make_shape(generate_numbers(13, 8, 0), (8, )))
# ary = generate_numbers(13, 8, 0)
ary


array([ 7, 10,  9,  1,  4,  2,  6,  8])

In [33]:
ary[0] , ary[2], ary[::2]  

(7, 9, array([7, 9, 4, 6]))

In [34]:
# np.array([1, 2, 3, 4], dtype=np.float32)
np.array(make_shape(generate_numbers(13, 8, 0), (8, )), dtype=np.float32)

array([1., 3., 7., 8., 9., 0., 4., 5.], dtype=float32)

In [35]:
# arr = np.array([1, 2, 3, 4])
arr = np.array(make_shape(generate_numbers(13, 8, 0), (8, )))
arr.dtype

dtype('int32')

In [36]:
arr.dtype = np.float32
arr

array([1.3e-44, 7.0e-45, 1.1e-44, 0.0e+00, 4.2e-45, 5.6e-45, 1.4e-45,
       8.4e-45], dtype=float32)

In [37]:
arr2 = arr.astype(np.float32)
arr2

array([1.3e-44, 7.0e-45, 1.1e-44, 0.0e+00, 4.2e-45, 5.6e-45, 1.4e-45,
       8.4e-45], dtype=float32)