In [1]:
import numpy as np
from scipy import sparse
from scipy.sparse import linalg

In [2]:
T = sparse.diags([-1, 2, -1], (-1, 0, 1), shape=(5, 5), format="csr")   # row based

In [ ]:
type(T)

In [3]:
temp = T.toarray()
type(temp)

numpy.ndarray

In [4]:
temp

array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

In [6]:
linalg.spsolve(T.tocsr(), np.array([1, 2, 3, 4, 5]))

array([ 5.83333333, 10.66666667, 13.5       , 13.33333333,  9.16666667])

In [7]:
T2 = sparse.diags([-1, 2, -1], (-1, 0, 1), shape=(5, 5), format="csc")  # column based
T2.toarray()

array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

In [8]:
type(T2)

scipy.sparse._csc.csc_matrix

In [9]:
linalg.spsolve(T2.tocsc(), np.array([1, 2, 3, 4, 5]))

array([ 5.83333333, 10.66666667, 13.5       , 13.33333333,  9.16666667])

In [10]:
T == T2

c:\Users\admin\.virtualenvs\data-science-BaewQYIE\lib\site-packages\IPython\core\interactiveshell.py:3508: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  exec(code_obj, self.user_global_ns, self.user_ns)


<5x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 25 stored elements in Compressed Sparse Row format>