In [2]:
import numpy as np

In [3]:
arr_a = np.array([1, 2, 3, 4])
arr_b = np.array([1, 0, -3, 1])

In [4]:
arr_a + arr_b 

array([2, 2, 0, 5])

In [5]:
arr_a - arr_b

array([0, 2, 6, 3])

In [6]:
arr_a * arr_b 

array([ 1,  0, -9,  4])

In [7]:
arr_b / arr_a 

array([ 1.  ,  0.  , -1.  ,  0.25])

In [8]:
arr_b**arr_a 

array([  1,   0, -27,   1])

In [9]:
arr = np.array([1, 2, 3, 4])

In [10]:
new = 2*arr
new

array([2, 4, 6, 8])